// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpsZX0-2t9ExRshvUK6hiA5eBZT2JFA7Y',
    appId: '1:707917630393:web:1b0ea69ce755a774d98468',
    messagingSenderId: '707917630393',
    projectId: 'burkina-app',
    authDomain: 'burkina-app.firebaseapp.com',
    storageBucket: 'burkina-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU1mh77-MDQnGO97f53zzHrt_ssgNGNfs',
    appId: '1:707917630393:android:6ddde91793c95cedd98468',
    messagingSenderId: '707917630393',
    projectId: 'burkina-app',
    storageBucket: 'burkina-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB_6vNrtyfMGm4YV4Oqu4U1UgG-ORgnAw',
    appId: '1:707917630393:ios:8d94b10c1114923cd98468',
    messagingSenderId: '707917630393',
    projectId: 'burkina-app',
    storageBucket: 'burkina-app.appspot.com',
    iosBundleId: 'com.example.cinema',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB_6vNrtyfMGm4YV4Oqu4U1UgG-ORgnAw',
    appId: '1:707917630393:ios:8d94b10c1114923cd98468',
    messagingSenderId: '707917630393',
    projectId: 'burkina-app',
    storageBucket: 'burkina-app.appspot.com',
    iosBundleId: 'com.example.cinema',
  );
}
